# Generated by Django 5.2.8 on 2025-12-04 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lingolab', '0002_learner'),
    ]

    operations = [
        migrations.AddField(
            model_name='learner',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
        migrations.AlterField(
            model_name='learner',
            name='score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.CreateModel(
            name='QuizTaken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=64)),
                ('type', models.CharField(max_length=64)),
                ('number_of_questions', models.IntegerField()),
                ('words_length', models.IntegerField()),
                ('time_limit', models.IntegerField()),
                ('learner_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learner', to='Lingolab.learner')),
            ],
        ),
    ]
