# Generated by Django 5.2.8 on 2025-12-04 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lingolab', '0003_learner_profile_picture_alter_learner_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learner',
            name='profile_picture',
            field=models.ImageField(blank=True, default='LingoLab/assets/profile/default.jpg', upload_to='profile_pics/'),
        ),
    ]
