# Generated by Django 5.2.8 on 2025-12-04 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lingolab', '0005_alter_learner_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learner',
            name='profile_picture',
            field=models.ImageField(blank=True, default='LingoLab/profile/default.jpg', upload_to='LingoLab/profile/'),
        ),
    ]
