# Generated by Django 5.2.8 on 2025-12-04 18:25

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lingolab', '0006_alter_learner_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiztaken',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quiztaken',
            name='correctness',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quiztaken',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='quiztaken',
            name='pause',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='quiztaken',
            name='pronunciation',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quiztaken',
            name='repetition',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='quiztaken',
            name='score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='quiztaken',
            name='speed',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='quiztaken',
            name='stutter',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='learner',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='quiztaken',
            name='language',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='quiztaken',
            name='learner_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzes_taken', to='Lingolab.learner'),
        ),
        migrations.AlterField(
            model_name='quiztaken',
            name='number_of_questions',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='quiztaken',
            name='time_limit',
            field=models.PositiveIntegerField(default=0, help_text='seconds'),
        ),
        migrations.AlterField(
            model_name='quiztaken',
            name='type',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='quiztaken',
            name='words_length',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
