# Generated by Django 5.2.8 on 2025-12-06 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lingolab', '0007_quiztaken_comment_quiztaken_correctness_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learner',
            name='score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
