# Generated by Django 5.2.8 on 2025-12-09 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lingolab', '0008_alter_learner_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiztaken',
            name='total_words',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
