# Generated by Django 5.2.8 on 2025-12-10 00:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lingolab', '0009_quiztaken_total_words'),
    ]

    operations = [
        migrations.CreateModel(
            name='currentQuizzes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_no', models.PositiveIntegerField(default=0)),
                ('item', models.TextField(blank=True)),
                ('speed', models.IntegerField(blank=True, null=True)),
                ('learner_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current_quizzes', to='Lingolab.learner')),
            ],
        ),
    ]
